sources:
- name: argo-cd
  repository: https://github.com/argoproj/argo-cd.git
  version: v3.3.2
  files: manifests/crds/*.yaml
  renovate:
    datasource: github-releases
    depName: argoproj/argo-cd

- name: external-secrets
  repository: https://github.com/external-secrets/external-secrets.git
  version: v2.1.0
  files: config/crds/bases/*.yaml
  renovate:
    datasource: github-releases
    depName: external-secrets/external-secrets

- name: keycloak
  repository: https://github.com/keycloak/keycloak-k8s-resources.git
  version: 26.5.5
  files: kubernetes/*.yml
  renovate:
    datasource: github-tags
    depName: keycloak/keycloak-k8s-resources

- name: kyverno
  repository: https://github.com/kyverno/kyverno.git
  version: v1.17.1
  helm: true
  files: charts/kyverno
  renovate:
    datasource: github-releases
    depName: kyverno/kyverno
